name: pull_json_data

on:
  schedule:
    - cron: '0 1 * * *'  # 每天凌晨1点执行
  push:
     branches:
        - main
  
jobs:
  
  build:
    runs-on: ubuntu-latest
    env:
      version: "4.6.0"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run os region decode
      run: |
        cd tools
        chmod +x region_decode
        ./region_decode "OSRELAndroid4.6.0" "cf1f175b8653373d" "5" "OS" "${version}" "https://osasiadispatch.yuanshen.com/query_cur_region"
    - name: Run cn region decode
      run: |
        cd tools
        chmod +x region_decode
        ./region_decode "CNRELAndroid4.6.0" "2a0793d37497c803" "4" "CN" "${version}" "https://cngfdispatch.yuanshen.com/query_cur_region"
    - name: Run region conve
      run: |
        cd tools
        chmod +x convert_region
        ./convert_region
    - name: Move file
      run: |
        mkdir ${version}
        cd tools
        mv ./output/* ../${version}/
        rm -rf ./intput
        chmod -x ./region_decode
        chmod -x ./convert_region
    - name: Push to repository
      run: |
          rsync -av --delete ./${version} ./json/
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git rm --cached -r ${version}
          git add -f "./json/${version}"
          git commit -m "update ${version}"
          git push --force https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}/
