name: pull_json_data

on:
  schedule:
    - cron: '0 1 * * *'  # 每天凌晨1点执行
  push:
     branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run os region decode
      run: |
        cd tools
        chmod +x region_decode
        ./region_decode OSRELAndroid4.1.0 64e149adf3705e93 5 OS "https://osasiadispatch.yuanshen.com/query_cur_region"
    - name: Run cn region decode
      run: |
        ./region_decode CNRELAndroid4.1.0 df7d21ffb348f73d 4 CN "https://cngfdispatch.yuanshen.com/query_cur_region"
    - name: Run region conve
      run: |
        cd tools
        chmod +x convert_region
        ./convert_region
    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: JSON
        path: tools/output
