name: pull_json_data

on:
  schedule:
    - cron: '0 1 * * *'  # 每天凌晨1点执行
  push:
     branches:
        - main
  workflow_dispatch:
jobs:
  
  build:
    runs-on: ubuntu-latest
    env:
      version: "5.1.0"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      # This is the version of the action for setting up Python, not the Python version.
      uses: actions/setup-python@v5
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.9'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    - name: Run os region decode
      run: |
        cd tools
        chmod +x region_decode
        ./region_decode "OSRELAndroid${version}" "d9067da913482dac" "5" "OS" "${version}" "https://osasiadispatch.yuanshen.com/query_cur_region"
    - name: Run cn region decode
      run: |
        cd tools
        chmod +x region_decode
        ./region_decode "CNRELAndroid${version}" "ca4641b3870b5dc1" "4" "CN" "${version}" "https://cngfdispatch.yuanshen.com/query_cur_region"
    - name: Run region conve
      run: |
        cd tools
        chmod +x convert_region
        ./convert_region

    - name: Move file
      run: |
        mkdir ${version}
        cd tools
        mv ./output/* ../${version}/
        rm -rf ./intput
        chmod -x ./convert_region
    - name:  Check update
      run: |
        python -m pip install --upgrade pip
        pip3 install jsondiff
        python ./tools/diff.py ${version}
        if [ -f ./is_run.txt ]; then
            echo "is_run.txt exists, continuing workflow"
            echo "IS_RUN=true" >> $GITHUB_ENV
            echo ${{ env.IS_RUN }}
          else
            echo "is_run.txt does not exist, skipping workflow"
            echo "IS_RUN=false" >> $GITHUB_ENV
            exit 0
          fi
    - name: Upload Action Runtime File
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.run_id }}
        path: "./${{ env.version }}"
    - name: Push to repository
      run: |
          rsync -av --delete ./${version} ./json/
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if [ "${{ env.IS_RUN }}" == "true" ]; then
            echo "IS_RUN is true, doing something..."
            git add -f "./json/${version}"
            git commit -m "update ${version} ${{ github.run_id }}"
            git push --force https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}/
          else
            echo "IS_RUN is false, skipping..."
          fi
