name: pull_json_data

on:
  schedule:
    - cron: '0 1 * * *'  # 每天凌晨1点执行
  push:
     branches:
        - main
  
jobs:
  
  build:
    runs-on: ubuntu-latest
    env:
      version: "4.2.0"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run os region decode
      run: |
        cd tools
        chmod +x region_decode
        ./region_decode "OSRELAndroid4.2.0" "953882be438da301" "5" "OS" "$version" "https://osasiadispatch.yuanshen.com/query_cur_region"
    - name: Run cn region decode
      run: |
        cd tools
        chmod +x region_decode
        ./region_decode "CNRELAndroid4.2.0" "589f66146a73d5cc" "4" "CN" "$version" "https://cngfdispatch.yuanshen.com/query_cur_region"
    - name: Run region conve
      run: |
        cd tools
        chmod +x convert_region
        ./convert_region
    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: "JSON"
        path: tools/output
