name: pull_json_data

on:
  schedule:
    - cron: '0 1 * * *'  # 每天凌晨1点执行
  push:
     branches:
        - main
  
jobs:
  
  build:
    runs-on: ubuntu-latest
    env:
      version: "4.6.0"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      # This is the version of the action for setting up Python, not the Python version.
      uses: actions/setup-python@v4
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.9'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    - name: Run os region decode
      run: |
        cd tools
        chmod +x region_decode
        ./region_decode "OSRELAndroid4.6.0" "cf1f175b8653373d" "5" "OS" "${version}" "https://osasiadispatch.yuanshen.com/query_cur_region"
    - name: Run cn region decode
      run: |
        cd tools
        chmod +x region_decode
        ./region_decode "CNRELAndroid4.6.0" "2a0793d37497c803" "4" "CN" "${version}" "https://cngfdispatch.yuanshen.com/query_cur_region"
    - name: Run region conve
      run: |
        cd tools
        chmod +x convert_region
        ./convert_region

    - name: Move file
      run: |
        mkdir ${version}
        cd tools
        mv ./output/* ../${version}/
        rm -rf ./intput
        chmod -x ./region_decode
        chmod -x ./convert_region
    - name:  Check update
      run: |
        python ./tools/diff.py
        if [ -f ./is_run.txt ]; then
          echo "is_run.txt exists, continuing workflow"
        else
          echo "is_run.txt does not exist, ending workflow"
          exit 0
        fi
    - name: Push to repository
      run: |
          rsync -av --delete ./${version} ./json/
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f "./json/${version}"
          git commit -m "update ${version}"
          git push --force https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}/
